### ISSUE TITLE
Typing numbers after a calculation adds numbers to the result instead of starting a new calculation.

### ISSUE THREAD

**Issue by bryzaguy** [grimxreaper/js-calc#2]
For example, pressing "2" "*" "3" "=" "4" should show "4" and not "64" because pressing numbers starts a new calculation.

**Comment by grimxreaper** [comment]
Fixed, please check if you can. Thank you.

**Comment by grimxreaper** [comment]
Fixed (had already fixed it along with other fixes before getting a chance to create a new branch for it)

**Comment by bryzaguy** [comment]
Appears to be fixed!
