### ISSUE TITLE
Pressing "=" multiple times does not repeat the operation.

### ISSUE THREAD

**Issue by bryzaguy** [grimxreaper/js-calc#3]
Pressing "=" multiple times should repeat the operation. For example, pressing "2" "*" "3" "=" "=" should show the result of multiplying 2 by 3 twice or "18".

**Comment by grimxreaper** [comment]
It is currently not repeating the operation, was it doing that for you?

**Comment by bryzaguy** [comment]
I'd like it to. It matches what other calculators do.

**Comment by grimxreaper** [comment]
Ohhh I see okay, I will have to fix the functionality on that.

**Comment by grimxreaper** [comment]
Fixed, please check if you can. Thank you.

**Comment by grimxreaper** [comment]
Fixed (had already fixed it along with other fixes before getting a chance to create a new branch for it)

**Comment by bryzaguy** [comment]
Seems fixed!
